services:
  kafka:
    container_name: kafka
    image: debezium/kafka:2.7.3.Final
    restart: unless-stopped
    environment:
      NODE_ID: 39
      CLUSTER_ID: debezium-postgres
      KAFKA_CONTROLLER_QUORUM_VOTERS: "45@10.21.34.45:19092,80@10.21.36.80:19092,39@10.21.34.39:19092"
      KAFKA_LISTENERS: "CLIENT://:29092,EXTERNAL://:9092,CONTROLLER://:19092"
      KAFKA_ADVERTISED_LISTENERS: "CLIENT://10.21.34.39:29092,EXTERNAL://10.21.34.39:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Replication Configuration
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_NUM_REPLICA_FETCHERS: 6
      KAFKA_REPLICA_FETCH_MAX_BYTES: 1048576
      KAFKA_REPLICA_FETCH_WAIT_MAX_MS: 500
      KAFKA_REPLICA_HIGH_WATERMARK_CHECKPOINT_INTERVAL_MS: 5000
      KAFKA_REPLICA_SOCKET_TIMEOUT_MS: 30000
      KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: 65536
      KAFKA_REPLICA_LAG_TIME_MAX_MS: 10000
      KAFKA_REPLICA_LAG_MAX_MESSAGES: 4000
      CONTROLLER_SOCKET_TIMEOUT_MS: 60000
      # LOG MESSAGE CONFIGURATION
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_MESSAGE_MAX_BYTES: 1000000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_LOG_INDEX_INTERVAL_BYTES: 4096
      KAFKA_LOG_INDEX_SIZE_MAX_BYTES: 10485760
      KAFKA_LOG_RETENTION_HOURS: 72
      KAFKA_LOG_FLUSH_INTERVAL_MS: 10000
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 20000
      KAFKA_LOG_FLUSH_SCHEDULER_INTERVAL_MS: 2000
      KAFKA_LOG_ROLL_HOURS: 72
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      # SOCKET SERVER CONFIGURATION
      KAFKA_NUM_IO_THREADS: 8
      KAFKA_NUM_NETWORK_THREADS: 8
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 1048576
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 1048576
      KAFKA_QUEUED_MAX_REQUESTS: 16
      KAFKA_FETCH_PURGATORY_PURGE_INTERVAL_REQUESTS: 100
      KAFKA_PRODUCER_PURGATORY_PURGE_INTERVAL_REQUESTS: 100
      HEAP_OPTS: '-Xmx3g -Xms1g'
      # MONITORING
      KAFKA_JMX_PORT: 9991
      KAFKA_JMX_HOST: 10.21.34.39
      KAFKA_JMX_OPTS: '-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9991 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false'
    ports:
      - 9092:9092
      - 9991:9991
      - 19092:19092
      - 29092:29092
    volumes:
      - /data/kafka:/kafka/data

#  schema-registry:
#    container_name: schema-registry
#    image: confluentinc/cp-schema-registry:latest
#    depends_on: [kafka]
#    restart: unless-stopped
#    environment:
#      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://10.21.34.45:9092,PLAINTEXT://10.21.36.80:9092,PLAINTEXT://10.21.34.39:9092"
#      SCHEMA_REGISTRY_GROUP_ID: debezium-postgres-schema-registry
#      SCHEMA_REGISTRY_HOST_NAME: schema-registry
#      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
#    ports:
#      - 8081:8081

  debezium:
    container_name: debezium
    image: debezium/connect-base
    depends_on: [kafka]
    restart: unless-stopped
    environment:
      BOOTSTRAP_SERVERS: "10.21.34.45:9092,10.21.36.80:9092,10.21.34.39:9092"
      GROUP_ID: debezium-postgres-cluster
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      CONNECT_REST_PORT: 8083
      HOST_NAME: 10.21.34.39
      ADVERTISED_HOST_NAME: 10.21.34.39
      ADVERTISED_PORT: 8083
      HEAP_OPTS: '-Xmx2g -Xms1g'
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 2
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 2
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 2
      CONNECT_CONFIG_STORAGE_MIN_INSYNC_REPLICAS: 2
      CONNECT_OFFSET_STORAGE_MIN_INSYNC_REPLICAS: 2
      CONNECT_STATUS_STORAGE_MIN_INSYNC_REPLICAS: 2
    volumes:
      - /data/jar/:/kafka/connect/
    ports:
      - 8083:8083

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on: [kafka, debezium]
    restart: unless-stopped
    ports:
      - 8090:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: debezium-staging-3439
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "10.21.34.45:9092,10.21.36.80:9092,10.21.34.39:9092"
      KAFKA_CLUSTERS_0_METRICS_PORT: 9991
      KAFKA_CLUSTERS_0_METRICS_TYPE: JMX
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium-postgres-cluster
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: 'http://debezium:8083'

  kafka-exporter:
    container_name: kafka-exporter
    image: danielqsj/kafka-exporter
    depends_on: [kafka]
    restart: unless-stopped
    command: ["--kafka.server=10.21.34.39:9092"]
    ports:
      - 9308:9308
